'use client';
import {useState,useEffect,useCallback} from 'react';
import {Plus,FileText,ShieldCheck,ArrowUpRight,Inbox,Link2,Clock3,Upload,Search,RefreshCw,Play,Pause,ScanLine,Save,KeyRound,ImageIcon,Settings2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {blankApplicant,fieldLabels,statuses,missingFields,applicantSuggestions,optionalFields,tripFields,defaultTripDates,type Applicant} from '@/lib/domain';
import PortraitEditor from './portrait-editor';

type Row={id:string;data:Applicant;status:string;step:string;note:string;passport:boolean;portrait:boolean;version:number;updated_at:number;job_type:string;payment_url?:string;application_number?:string;official_url?:string};
async function api(path:string,method='GET',body?:unknown):Promise<any>{const res=await fetch('/api/'+path,{method,headers:body instanceof FormData?{}:{'Content-Type':'application/json'},body:body?body instanceof FormData?body:JSON.stringify(body):undefined});const data:any=await res.json();if(!res.ok)throw Error(data.error||'Xatolik');return data;}
const options:Partial<Record<keyof Applicant,string[]>>={gender:['Male','Female'],maritalStatus:['Single','Married','Divorced','Widow','Other'],visitPurpose:['Umrah','Leisure','Family & Relatives','Event'],accommodationType:['Hotel','Residential']};
const localized:Record<string,string>={Male:'Erkak',Female:'Ayol',Single:'Turmush qurmagan',Married:'Turmush qurgan',Divorced:'Ajrashgan',Widow:'Beva',Other:'Boshqa',Umrah:'Umra',Leisure:'Turizm','Family & Relatives':'Qarindoshlarni ko‘rish',Event:'Tadbir',Hotel:'Mehmonxona',Residential:'Mezbon / qarindosh' };
const dateFields=['birthDate','issueDate','expiryDate','travelDate','departureDate'];
export default function Operator({miniApp=false}:{miniApp?:boolean}){
 const [rows,setRows]=useState<Row[]>([]),[connections,setConnections]=useState<any>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const [tripOpen,setTripOpen]=useState(false),[tripData,setTripData]=useState<Applicant>({...blankApplicant});
 const [telegramOpen,setTelegramOpen]=useState(false),[telegramData,setTelegramData]=useState({botId:'',botUsername:'',operatorId:''});
 const [creationKey,setCreationKey]=useState('');
 const [selected,setSelected]=useState<Row|null>(null),[data,setData]=useState<Applicant>({...blankApplicant}),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false);
 const [filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[events,setEvents]=useState<any[]>([]),[pairOpen,setPairOpen]=useState(false),[token,setToken]=useState(''),[cropOpen,setCropOpen]=useState(false);
 const refresh=useCallback(async()=>{try{const [r,c]=await Promise.all([api('applications'),api('settings')]);setRows(r);setConnections(c);setError('');}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{refresh();const t=setInterval(refresh,15000);return()=>clearInterval(t)},[refresh]);
 const execute=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setSuccess('');try{await fn();await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const edit=async(row?:Row)=>{setCreationKey(crypto.randomUUID());setSelected(row||null);setData(row?{...blankApplicant,...row.data}:{...blankApplicant,...defaultTripDates(),...Object.fromEntries(Object.entries(connections.tripDefaults||{}).filter(([,v])=>v))});setConfirmed(false);setOpen(true);setEvents([]);if(row)try{setEvents(await api(`applications/${row.id}/events`))}catch{}};
 const save=async()=>{let current:Row;if(selected){await api('applications/'+selected.id,'PATCH',{data,version:selected.version});current=await api('applications/'+selected.id)}else current=await api('applications','POST',{data,sourceKey:creationKey});setSelected(current);setData(current.data);setSuccess('Ma’lumotlar saqlandi');return current;};
 const upload=async(file:File,kind:'passport'|'portrait')=>execute(async()=>{const row=selected||await save();const form=new FormData();form.set('file',file);form.set('kind',kind);await api(`applications/${row.id}/upload`,'POST',form);if(kind==='passport')await api(`applications/${row.id}/queue`,'POST',{job:'extract'});setSelected(await api(`applications/${row.id}`));setConfirmed(false);setSuccess(kind==='passport'?'Pasport saqlandi va o‘qish navbatiga qo‘shildi.':'Portret saqlandi.');});
 const queue=()=>execute(async()=>{const row=await save();await api(`applications/${row.id}/queue`,'POST',{job:'visa',confirmed});setOpen(false);setSuccess('Ariza navbatga qo‘shildi');});
 const locked=!!selected&&['running','queued','payment_ready','paid'].includes(selected.status);
 const suggestions=applicantSuggestions(data);
 useEffect(()=>{if(!selected||!['running','queued'].includes(selected.status))return;const latest=rows.find(r=>r.id===selected.id);if(latest&&latest.version!==selected.version){setSelected(latest);setData({...blankApplicant,...latest.data});setConfirmed(false);}},[rows,selected]);
 const visible=rows.filter(r=>(filter==='all'||(filter==='waiting'?['queued','running'].includes(r.status):r.status==='payment_ready'))&&`${r.data.firstName} ${r.data.lastName} ${r.data.passportNumber}`.toLowerCase().includes(search.toLowerCase()));
 const counts=[rows.length,rows.filter(r=>['queued','running'].includes(r.status)).length,rows.filter(r=>['draft','needs_input','needs_auth','needs_review','failed'].includes(r.status)).length,rows.filter(r=>r.status==='payment_ready').length];
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();const register=(tool:any)=>Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});
 register({name:'list_evisa_applications',description:'List saved applications and their current status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No arguments accepted');const r=await api('applications');setRows(r);return r.map((x:Row)=>({id:x.id,name:x.data.lastName+' '+x.data.firstName,status:x.status}));}});
 register({name:'start_evisa_application',description:'Open an empty application editor. Does not save or submit an application.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No arguments accepted');await edit();return {editor:'open',saved:false}}});return()=>controller.abort();},[]);
 return <div className={miniApp?"shell mini-app":"shell"}><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><FileText size={22}/></span>eVisa <b>Operator</b></a><span className="private"><ShieldCheck size={16}/> Xususiy ish maydoni</span></header>
 <main className="workspace">{!miniApp&&<div className="eyebrow">SAUDI ARABIA / ARIZALAR MARKAZI</div>}<div className="heading"><div><h1>{miniApp?"Arizalarim":"Arizalarni boshqaring."}</h1>{!miniApp&&<p>Pasportdan to‘lovga tayyor arizagacha.</p>}</div><div className="heading-actions">{!miniApp&&<Button variant="outline" onClick={()=>{setTelegramData(connections.telegramApp||{botId:"",botUsername:"",operatorId:""});setTelegramOpen(true)}}>Telegram Mini App</Button>}<Button variant="outline" onClick={()=>{setTripData({...blankApplicant,...connections.tripDefaults});setTripOpen(true)}}><Settings2 size={17}/> Safar sozlamalari</Button><Button className="primary" onClick={()=>edit()}><Plus size={18}/> Yangi ariza</Button></div></div>
 {error&&<div className="notice error" role="alert">{error} <button onClick={refresh}>Qayta tekshirish</button></div>}{success&&<div className="notice" role="status">{success}</div>}
 <div className="overview">{['Jami arizalar','Navbatda','Ma’lumot kerak','To‘lovga tayyor'].map((s,i)=><div key={s} className={'stat '+(i===3?'highlight':'')}><span>{s}</span><strong>{loading?'—':counts[i]} {i===3&&<ArrowUpRight/>}</strong><small>{['Ish maydonidagi arizalar','Avtomatik to‘ldirishni kutmoqda','Tekshirish uchun qaytarilgan','Davomini siz bajarasiz'][i]}</small></div>)}</div>
 <div className="board"><section className="applications"><div className="section-heading"><h2>Arizalar navbati</h2><span className="count">{rows.length} ta</span><Button variant="ghost" size="icon" aria-label="Yangilash" onClick={refresh}><RefreshCw size={16}/></Button></div><div className="toolbar"><Tabs value={filter} onValueChange={setFilter}><TabsList><TabsTrigger value="all">Barchasi</TabsTrigger><TabsTrigger value="waiting">Navbatda</TabsTrigger><TabsTrigger value="payment">To‘lovga tayyor</TabsTrigger></TabsList></Tabs><div className="search"><Search size={16}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ism yoki pasport raqami" aria-label="Arizalarni qidirish"/></div></div><Table><TableHeader><TableRow><TableHead>ARIZACHI</TableHead><TableHead>HOLATI</TableHead><TableHead>BOSQICH</TableHead><TableHead>YANGILANGAN</TableHead></TableRow></TableHeader><TableBody>{visible.map(r=><TableRow key={r.id}><TableCell><button className="app-name" onClick={()=>edit(r)}>{r.data.lastName||'Yangi'} {r.data.firstName||'ariza'}<small>{r.data.passportNumber?r.data.passportNumber.slice(0,2)+'••••'+r.data.passportNumber.slice(-3):'Pasportni o‘qish kutilmoqda'}</small></button></TableCell><TableCell><span className={'badge '+r.status}>{statuses[r.status]}</span></TableCell><TableCell>{r.job_type==='extract'?'Pasportni o‘qish':({personal:'Shaxsiy ma’lumotlar',passport:'Pasport',review:'Tekshirish',payment:'To‘lov',upload:'Ma’lumot yig‘ish'} as any)[r.step]||r.step}</TableCell><TableCell>{new Date(r.updated_at).toLocaleString('uz-UZ',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</TableCell></TableRow>)}{!visible.length&&<TableRow><TableCell colSpan={4}><div className="empty"><span><Inbox size={30}/></span><h3>{loading?'Arizalar yuklanmoqda':rows.length?'Ariza topilmadi':'Birinchi arizani qo‘shing'}</h3><p>{rows.length?'Qidiruv yoki holat filtrini o‘zgartiring.':'Pasport rasmini yuklang va arizachi ma’lumotlarini kiriting.'}</p><Button variant="outline" onClick={()=>edit()}><Plus size={16}/> Ariza qo‘shish</Button></div></TableCell></TableRow>}</TableBody></Table></section>
 <aside><div className="connection"><h2><Link2 size={18}/> Ulanishlar</h2>{[['visa','Saudi eVisa akkaunti'],['gmail','Gmail'],['telegram','Telegram bot']].map(([key,label])=><div className="connection-row" key={key}><span>{label}</span><small>{connections.online&&connections.connections?.[key]?(key==='gmail'?'Sozlangan':'Ulangan'):'Ulanmagan'}</small></div>)}<p>{connections.online?'Bajaruvchi bilan aloqa mavjud.':'Bajaruvchi hali ulanmagan. Arizalar navbatda saqlanadi.'}</p><Button variant="outline" className="w-full mt-4" onClick={()=>setPairOpen(true)} disabled={miniApp}><KeyRound size={16}/> Bajaruvchini ulash</Button></div><div className="flow"><h2>Ish tartibi</h2>{['Pasportni yuklash','Ma’lumotlarni tekshirish','Saytda to‘ldirish','To‘lovni davom ettirish'].map((x,i)=><div className="flow-row" key={x}><span>{i+1}</span>{x}{i===3&&<ArrowUpRight size={16}/>}</div>)}<div className="flow-note"><Clock3 size={17}/><p>Bot to‘lov oldida to‘xtaydi.</p></div></div><div className="rollout">Ulanish sinovi kerak: pasport, sug‘urta va to‘lovga o‘tish bosqichlari hali to‘liq tekshirilmagan.</div></aside></div>
 <footer><span>eVisa Operator</span><span>Bir akkaunt. Tartibli navbat.</span></footer></main>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{selected?'Ariza ma’lumotlari':'Yangi ariza'}</DialogTitle><DialogDescription>Ma’lumotlar pasport va arizachining javoblariga mos bo‘lishi kerak.</DialogDescription></DialogHeader>
 {error&&<div className="notice error" role="alert">{error}</div>}{selected?.note&&<div className="notice">{selected.note}</div>}
 <div className="file-grid"><div className="upload-zone"><Upload/><strong>Pasport rasmi</strong><p>{selected?.passport?'Yuklangan':'JPG yoki PNG · 10 MB gacha'}</p><Input aria-label="Pasport rasmi" type="file" accept="image/jpeg,image/png" disabled={busy||locked} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f,'passport');e.target.value=''}}/>{selected?.passport&&<a href={`/api/applications/${selected.id}/file?kind=passport`} target="_blank" rel="noreferrer">Pasportni ko‘rish</a>}</div><div className="upload-zone"><ImageIcon/><strong>Portret · 200 × 200</strong><p>{selected?.portrait?'Tayyor · quyida tekshiring':'Pasportni o‘qishda avtomatik kesiladi'}</p>{selected?.portrait&&<img width={120} height={120} className="portrait-preview" alt="Tekshirish uchun 200 × 200 portret" src={`/api/applications/${selected.id}/file?kind=portrait&v=${selected.version}`}/>} <Input aria-label="Portret" type="file" accept="image/jpeg,image/png" disabled={busy||locked} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f,'portrait');e.target.value=''}}/>{selected?.passport&&<Button variant="outline" disabled={busy||locked} onClick={()=>setCropOpen(true)}>Kesishni tuzatish</Button>}</div></div>
 {!locked&&suggestions.length>0&&<section className="suggestions"><h3>Tekshirish uchun takliflar</h3><p>Bu qiymatlar pasport bilan tasdiqlanmagan. Faqat arizachi uchun to‘g‘ri bo‘lsa qo‘llang.</p><dl>{suggestions.map(s=><div key={s.field}><dt>{fieldLabels[s.field]}</dt><dd><strong>{localized[s.value]||s.value}</strong><small>{s.reason}</small></dd></div>)}</dl><Button variant="outline" disabled={busy} onClick={()=>{setData(d=>({...d,...Object.fromEntries(suggestions.map(s=>[s.field,s.value]))}));setConfirmed(false)}}>To‘g‘riligini tasdiqlab qo‘llash</Button></section>}
 <div className="form-grid">{(Object.keys(blankApplicant) as (keyof Applicant)[]).map(k=><label key={k}><span>{fieldLabels[k]}{!optionalFields.includes(k)&&!(data.accommodationType==='Hotel'&&['saudiCity','saudiAddress'].includes(k))&&' *'}</span>{options[k]?<Select value={data[k]} disabled={locked||busy} onValueChange={v=>{setData(d=>({...d,[k]:v}));setConfirmed(false)}}><SelectTrigger className="w-full"><SelectValue placeholder="Tanlang"/></SelectTrigger><SelectContent>{options[k]!.map(v=><SelectItem key={v} value={v}>{localized[v]||v}</SelectItem>)}</SelectContent></Select>:<Input value={data[k]} type={dateFields.includes(k)?'date':'text'} disabled={locked||busy||k==='postalCode'} placeholder={k==='postalCode'?'Bo‘sh qoldiriladi':undefined} onChange={e=>{setData(d=>({...d,[k]:e.target.value}));setConfirmed(false)}}/>}</label>)}</div>
 {!locked&&<label className="confirm"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/><span>Oilaviy holat, kasb, haqiqiy yashash manzili va portretni tekshirdim; ma’lumotlar to‘g‘ri; ushbu arizachining arizasini tayyorlashga vakolatim bor.</span></label>}
 {selected?.official_url&&<p><a href={selected.official_url} target="_blank" rel="noreferrer">Rasmiy qoralama · {selected.application_number} <ArrowUpRight size={14}/></a></p>}
 {selected?.payment_url&&selected.status==='payment_ready'&&<a className="payment-link" href={selected.payment_url} target="_blank" rel="noreferrer">To‘lovni davom ettirish <ArrowUpRight size={18}/></a>}
 {!locked&&missingFields(data,!!selected?.portrait).length>0&&<div className="notice missing-fields"><strong>To‘ldirish kerak:</strong> {missingFields(data,!!selected?.portrait).join(", ")}</div>}
 <div className="editor-actions">{selected?.status==='queued'?<Button variant="outline" disabled={busy} onClick={()=>execute(async()=>{await api(`applications/${selected.id}/pause`,'POST');setSelected(await api(`applications/${selected.id}`))})}><Pause size={16}/> Navbatdan chiqarish</Button>:<><Button variant="outline" disabled={busy||locked} onClick={()=>execute(async()=>{await save()})}><Save size={16}/> Saqlash</Button>{selected?.passport&&<Button variant="outline" disabled={busy||locked} onClick={()=>execute(async()=>{const row=await save();await api(`applications/${row.id}/queue`,'POST',{job:'extract'});setSelected(await api(`applications/${row.id}`));setConfirmed(false)})}><ScanLine size={16}/> Pasportni qayta ishlash</Button>}<Button disabled={busy||locked||!confirmed||missingFields(data,!!selected?.portrait).length>0} onClick={queue}><Play size={16}/> To‘ldirishni boshlash</Button></>}</div>
 {events.length>0&&<details><summary>Ariza tarixi</summary>{events.map((e,i)=><p className="event" key={i}>{new Date(e.created_at).toLocaleString('uz-UZ')} · {e.message}</p>)}</details>}
 </DialogContent></Dialog>
 <Dialog open={tripOpen} onOpenChange={setTripOpen}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>Safar sozlamalari</DialogTitle><DialogDescription>Saqlangan qiymatlar yangi arizalarga qo‘yiladi. Har bir arizachi uchun haqiqiy safar ma’lumotlarini tekshiring.</DialogDescription></DialogHeader><div className="notice">Kirish va chiqish — kutilayotgan safar sanalari. Bu maydonlar vizaning amal qilish muddatini belgilamaydi.</div><div className="form-grid">{tripFields.map(k=><label key={k}><span>{fieldLabels[k]}</span>{options[k]?<Select value={tripData[k]} onValueChange={v=>setTripData(d=>({...d,[k]:v}))}><SelectTrigger><SelectValue placeholder="Tanlang"/></SelectTrigger><SelectContent>{options[k]!.map(v=><SelectItem key={v} value={v}>{localized[v]||v}</SelectItem>)}</SelectContent></Select>:<Input value={tripData[k]} type={dateFields.includes(k)?'date':'text'} onChange={e=>setTripData(d=>({...d,[k]:e.target.value}))}/>}</label>)}</div><Button disabled={busy} onClick={()=>execute(async()=>{await api('trip-defaults','POST',{data:tripData});setTripOpen(false);setSuccess('Yangi arizalar uchun safar sozlamalari saqlandi')})}>Safar sozlamalarini saqlash</Button></DialogContent></Dialog>
 {!miniApp&&<Dialog open={telegramOpen} onOpenChange={setTelegramOpen}><DialogContent><DialogHeader><DialogTitle>Telegram Mini App</DialogTitle><DialogDescription>Ilovaga kiradigan bot va yagona operatorni belgilang. Bu oynaga bot tokeni kiritilmaydi.</DialogDescription></DialogHeader>{error&&<div className="notice error" role="alert">{error}</div>}<label>Bot ID<Input aria-label="Bot ID" value={telegramData.botId} onChange={e=>setTelegramData(d=>({...d,botId:e.target.value}))}/></label><label>Bot username<Input aria-label="Bot username" value={telegramData.botUsername} onChange={e=>setTelegramData(d=>({...d,botUsername:e.target.value.replace(/^@/, '')}))}/></label><label>Operator Telegram ID<Input aria-label="Operator Telegram ID" value={telegramData.operatorId} onChange={e=>setTelegramData(d=>({...d,operatorId:e.target.value}))}/></label><Button disabled={busy} onClick={()=>execute(async()=>{await api('telegram/register','POST',telegramData);setTelegramOpen(false);setSuccess('Telegram Mini App operatori saqlandi')})}>Telegram operatorini saqlash</Button></DialogContent></Dialog>}
 <Dialog open={pairOpen} onOpenChange={setPairOpen}><DialogContent><DialogHeader><DialogTitle>Bajaruvchini ulash</DialogTitle><DialogDescription>Serverdagi bot shu paneldan arizalarni oladi. Bitta bajaruvchi barcha arizalarni navbat bilan bajaradi.</DialogDescription></DialogHeader><p>Telegram, Gmail va Saudi akkaunti serverdagi sozlamalarda bir marta ulanadi.</p>{token?<><p>Quyidagi kalitni serverdagi PANEL_TOKEN sozlamasiga kiriting. U qayta ko‘rsatilmaydi.</p><Input aria-label="Ulash kaliti" value={token} readOnly/><Button onClick={()=>navigator.clipboard.writeText(token).then(()=>setSuccess('Kalit nusxalandi')).catch(()=>setError('Kalitni qo‘lda nusxalang'))}>Kalitni nusxalash</Button></>:<Button disabled={busy} onClick={()=>execute(async()=>{const r=await api('pair','POST',{});setToken(r.token)})}>{connections.paired?'Ulash kalitini yangilash':'Ulash kalitini olish'}</Button>}{connections.paired&&!token&&<p>Kalit yangilansa, eski bajaruvchiga yangi kalitni kiritish kerak bo‘ladi.</p>}</DialogContent></Dialog>
 {selected&&<PortraitEditor open={cropOpen} onOpenChange={setCropOpen} url={`/api/applications/${selected.id}/file?kind=passport`} onSave={async file=>{await upload(file,'portrait');setCropOpen(false)}}/>}
 </div>
}
