'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogHeader} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Slider} from '@/components/ui/slider';
export default function PortraitEditor({open,onOpenChange,url,onSave}:{open:boolean;onOpenChange:(v:boolean)=>void;url:string;onSave:(f:File)=>Promise<void>}){
 const canvas=useRef<HTMLCanvasElement>(null),img=useRef<HTMLImageElement|null>(null);const [x,X]=useState(8),[y,Y]=useState(60),[size,S]=useState(27),[ready,R]=useState(false),[error,E]=useState(''),[busy,B]=useState(false);
 useEffect(()=>{if(!open)return;R(false);E('');const i=new Image();i.onload=()=>{img.current=i;R(true)};i.onerror=()=>E('Rasm ochilmadi');i.src=url;return()=>{i.onload=null;i.onerror=null}},[open,url]);
 useEffect(()=>{const c=canvas.current,i=img.current;if(!c||!i||!ready)return;const ctx=c.getContext('2d')!;const side=Math.min(i.width,i.height)*size/100;const left=(i.width-side)*x/100,top=(i.height-side)*y/100;ctx.fillStyle='white';ctx.fillRect(0,0,200,200);ctx.drawImage(i,left,top,side,side,0,0,200,200)},[x,y,size,ready]);
 async function save(){B(true);E('');try{const blob=await new Promise<Blob|null>(r=>canvas.current?.toBlob(r,'image/jpeg',.95));if(!blob||blob.size<5000||blob.size>100000)throw Error('Rasm hajmi 5–100 KB bo‘lishi kerak. Kesish chegarasini o‘zgartiring.');await onSave(new File([blob],'portrait.jpg',{type:'image/jpeg'}))}catch(e){E((e as Error).message)}finally{B(false)}}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Portretni kesish</DialogTitle><DialogDescription>Yuz va yelka yuqori qismini joylang. Himoya naqshlari va eski suratni kesish orqali tuzatib bo‘lmaydi.</DialogDescription></DialogHeader><canvas ref={canvas} width={200} height={200} style={{margin:'auto',borderRadius:8,border:'1px solid #ddd'}}/>{[['Gorizontal',x,X],['Vertikal',y,Y],['Kesish o‘lchami',size,S]].map(([label,value,set])=><label key={String(label)} className="slider-field">{String(label)}<Slider min={label==='Kesish o‘lchami'?10:0} max={100} step={1} value={[value as number]} onValueChange={v=>(set as (n:number)=>void)(v[0])}/></label>)}{error&&<p role="alert">{error}</p>}<Button onClick={save} disabled={!ready||busy}>200 × 200 portretni saqlash</Button></DialogContent></Dialog>
}
